[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[env]
PORT = { default = "8000" }
PYTHON_VERSION = { default = "3.11" }